n: 1
m: 5
r: 7
seed: 0
wandb_name: mixup_known
device: 2
abs: false
top_1: false
gamma: 1.0
logit_avg: true
score_calculator:
  class_path: mixup.mixdiff_msp.MixDiffMaxSofmaxProb
  init_args:
    batch_size: 2048
    utilize_mixup: true