n: 3
m: 3
r: 3
seed: 0
wandb_name: mixup_v2
device: 1
abs: false
top_1: false
gamma: 1.0
score_calculator:
  class_path: mixup.mixdiff_zoc.MixDiffZOC
  init_args:
    zoc_checkpoint_path: trained_models/COCO/ViT-B32/model.pt