n: 15
m: 10
r: 7
seed: 0
wandb_name: mixup_test
device: 2
abs: false
top_1: false
gamma: 1.0
score_calculator:
  class_path: mixup.ood_score_calculators.mixdiff_entropy.MixDiffEntropy
  init_args:
    batch_size: 2048
datamodule:
  class_path: mixup.ood_datamodules.cifar10_ood.CIFAR10OODDataset
