n: 2
m: 2
r: 3
seed: 0
wandb_name: mixup_test
device: 2
abs: false
top_1: false
gamma: 1.0
score_calculator:
  class_path: mixup.ood_score_calculators.mixdiff_msp.MixDiffMaxSofmaxProb
  init_args:
    batch_size: 2048
datamodule:
  class_path: mixup.ood_datamodules.tiny_imagenet_ood.TinyImageNetOODDataset
